# 2.1 初めてのニューラルネットワーク

## mnistデータセットの読み込み

In [32]:
from keras.datasets import mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

In [34]:
# .shape 配列のサイズ　定義してある配列が何行何列なのか
train_images.shape

(60000, 28, 28)

In [35]:
# データ数
len(train_images)

60000

In [36]:
# ラベル（1～9）
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

## ニューラスネットワークのアーキテクチャ

In [38]:
from keras import models
from keras import layers

network = models.Sequential()
network.add(layers.Dense(512, activation='relu', input_shape=(28*28, )))
network.add(layers.Dense(10, activation='softmax'))

このニューラルネットは、２つの密に結合された層（Dence）で構成されている。⇛全結合層

最後の層は10個のユニットからなるソフトマックス層であり、合計すると１になる10個の確率スコアを含む配列を返す。

ニューラルネットを訓練する準備を整えるには、コンパイルステップとして以下の要素を選択する必要がある。

①損失関数

訓練データでのネットワークの性能をどのように評価するのか、そしてネットワークを正しい方向にどのように向かわせるのかを決める手法

②オプティマイザ

与えられたデータを損失関数に基づいてネットワークが自身を更新するメカニズム

③訓練とテストを監視するための指標

ここでは正解率のみを考慮する

In [39]:
# コンパイルステップ
network.compile(optimizer='rmsprop',
               loss='categorical_crossentropy',
               metrics=['accuracy'])

画像データの前処理として、データの形状を変換する。具体的には、すべての値を0,1の区間に収まるようスケーリングする。

今回使用するデータは型がunit8、形状が(60000,28,28)の配列に格納されている。この配列には0,255の区間の値が格納されている。

このデータを型がfloat32、形状が(60000, 28*28)で0~1の値が含まれた配列に変換する。

In [40]:
train_images

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ..., 
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ..., 
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ..., 
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ..., 
       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ..., 
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ..., 
        [0, 0, 0, 

In [45]:
# 画像データの準備
train_images = train_images.reshape((60000, 28*28, ))
train_images = train_images.astype('float32') / 255

test_images = test_images.reshape((10000, 28*28, ))
test_images = test_images.astype('float32') / 255

In [46]:
train_images

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]], dtype=float32)

In [47]:
# ラベルをカテゴリ値でエンコード
from keras.utils import to_categorical

train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

In [48]:
# 適合
network.fit(train_images, train_labels, epochs=5, batch_size=128)

Epoch 1/5
60000/60000 [==============================] - 2s 40us/step - loss: 1.4620 - acc: 0.6661
Epoch 2/5
60000/60000 [==============================] - 2s 40us/step - loss: 0.5781 - acc: 0.8556
Epoch 3/5
60000/60000 [==============================] - 3s 47us/step - loss: 0.4066 - acc: 0.8888
Epoch 4/5
60000/60000 [==============================] - 2s 41us/step - loss: 0.3501 - acc: 0.9014
Epoch 5/5
60000/60000 [==============================] - 2s 38us/step - loss: 0.3218 - acc: 0.9076


In [49]:
# 正解率
test_loss, test_acc = network.evaluate(test_images, test_labels)
print(test_acc)

10000/10000 [==============================] - 0s 28us/step
0.9116
