# ニューラルネットワークでのデータ表現

多次元のNumPy配列に格納されたデータはテンソルとも呼ばれる。一般に、機械学習システムはすべて、基本的なデータ構造としてテンソルを使用する。

基本的に、テンソルはデータのコンテナ（入れ物）。行列は２次元のテンソルであり、テンソルとは、任意の数の次元に対して、行列を一般化したもの。

参考：https://qiita.com/mucunwuxian/items/10cb0f014964446fa2a3

## スカラー：０次元テンソル

数値を一つしか含んでいないテンソルは、スカラーと呼ばれる。スカラーは「スカラーテンソル」「０次元テンソル」とも言う。
numpyのfloat32型やfloat64型の数値はスカラーテンソルである。

numpyでテンソル軸の数を表示するには、ndim属性を使用する。スカラーテンソルの軸は0となる。テンソルの軸の数は階級（rank）とも呼ばれる。

In [8]:
import numpy as np
x = np.array(12)
x

array(12)

In [9]:
x.ndim

0

## ベクトル：１次元テンソル
数値の配列はベクトルと呼ばれる。ベクトルは１次元テンソルであり、軸は一つ。

In [10]:
x = np.array([2,6,22,67])
x

array([ 2,  6, 22, 67])

In [11]:
x.ndim

1

## 行列：２次元テンソル

ベクトルの配列は行列。行列は行と列の２軸を持つ２次元テンソルである。

In [15]:
x = np.array([[2,6,22,67],
            [2,4,2,1],
            [11,61,5,9]])
x

array([[ 2,  6, 22, 67],
       [ 2,  4,  2,  1],
       [11, 61,  5,  9]])

In [16]:
x.ndim

2

## ３次元テンソルとより高次元のテンソル

In [17]:
x = np.array([[[2,6,22,67],
            [2,4,2,1],
            [11,61,5,9]],
              [[2,6,22,67],
            [2,4,2,1],
            [11,61,5,9]]])
x

array([[[ 2,  6, 22, 67],
        [ 2,  4,  2,  1],
        [11, 61,  5,  9]],

       [[ 2,  6, 22, 67],
        [ 2,  4,  2,  1],
        [11, 61,  5,  9]]])

In [19]:
x.ndim

3